[workspace]
resolver = "2"
members = [
  "crates/sim3d",
  "crates/game",
]

default-members = [
  "crates/game",
]

[workspace.dependencies]
glam = "0.27"
serde = { version = "1.0", features = ["derive"] }
bytemuck = { version = "1.14", features = ["derive"] }
