[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23"
winit = "0.30"
pollster = "0.4"
bytemuck = { version = "1.14", features = ["derive"] }
glam = { workspace = true }
sim = { path = "../sim" }
sim3d = { path = "../sim3d" }
env_logger = "0.11"
log = "0.4"
